<?php
/**
 * Resource class handles resource links and resource types
**/
class Resource {
    /**
     * Auto generated by mySQL and can be null at creation
    **/
    private $resourceId;
    
    /**
     * Auto generated by mySQL and can be null at creation
    **/
    private $adminId;
    
    /**
     * String, the URL of the link 
    **/
    private $resourceLink;
    
    /**
     * String title of the link, video or audio 
    **/
    private $resourceTitle;
    
    /**
     * String that states how will the resource be displayed, video, audio, other website? 
    **/
    private $resourceType;
    
    /**
     *constructor for resource
     *
     *@param Int for the resource id
     *@param Int for the user id
     *@param string The URL the came from
     *@param string Title of the resource
     *@param string Type of resource to format
     *@throws UnexceptedValueException if inputs are of the incorrect types or urls
     *@throws RangesException if the inputs contain invalid values
     **/
    public function __construct($resourceId, $adminId, $resourceLink, $resourceTitle, $resourceType) {
        try{
            $this ->resourceId($newResourceId);
            $this ->adminId($newAdminId);
            $this ->resourceLink($newResourceLink);
            $this ->resourceType($newResourceType);
            $this ->resourceId($newResourceId);
        } catch(UnexpectedValueException $unexpectedValue) {
            // rethrow to caller
            throw(UnexpectedValueException("Unable to construct resource", 0, $unexpectedValue));  
        } catch(RangeException $range) {
            // rethrow to caller
            throw(new RangeException("Unable to construct resource", 0, $range));
        }
    }
    
    /**
     * Accessor method for resource id
     *
     * @return integer value of resource id
     *
    **/
     public function getResourceId() {
        
    }
    /**
     * Mutator method for resource id
     *
     * @param mixed new value of a resource id or null if a new object
     * @throws UnexpectedValueException if input is not an integer
     * @throws a RangeException if resource id isn't positive 
    **/
    public function setResourceId($newResourceId) {
        // zeroth, allow null if this is a new object
        if($newResourceId === null) {
            $this->resourceId = null;
            return;
    }
    
    // first, trim the input
    $newResourceId = trim($newResourceId);
    
    // second, check if resource id is an integer
    if((filter_var($newResourceId, FILTER_VALIDATE_INT)) === false) {
        throw(UnexpectedValueException("resource id $newResourceId is not a number"));
    }
    
    // third, convert resource id to an integer and ensure it's positive
    $newResourceId = intval($newResourceId);
    if($resourceId<= 0) {
        throw(new RangeException("resource id $resourceId must be a positive number"));
    }
    
    // finally, the resource id is clean and can be taken out of quarantine
    $this->resourceId = $newResourceId;
}
    
    /**
     * Accessor method for admin id
     *
     * @return integer value of admin id
    **/
    public function getAdminId() {
        
    }
    
    /**
     * Mutator method for Admin id
     *
     * @param mixed value of user id or allow to be null if it's a new object
     * @throws UnexpectedValueException if user id is not an integer
     * @throws RangeException if user id isn't positive
    **/
    public function setAdminId($newAdminId) {
        // zeroth, allow null if this is a new object
        if($newAdminId === null) {
            $this->adminId = null;
            return;
        }
        
        // first, trim the input
        $$newAdminId = trim($newAdminId);
        
        // second, check if the admin id is an integer
        if((filter_var($newAdminId, FILTER_VALIDATE_INT)) === false) {
            throw(new UnexpectedValueException("admin id $newAdminId is not an integer"));   
        }
        
        // third, convert admin id and ensure it's positive
        $newAdminId = intval($newAdminId);
        if($newAdminId <= 0) {
            throw(new RangeException("user id $newAdminId must be a positive integer"));
        }
        
        // finally, admin id is clean and can be removed from quarantine
        $this->adminId = $newAdminId;
    }
    
    /**
     * Accessor method for resource link
     *
     * @return string of resource link URL
    **/
    public function getResourceLink() {
        
    }
    
    /**
     * Mutator method for resource link URL
     *
     * 
    **/
    public function setResourceLink($newResourceLink) {
        if(gettype($newResourceLink) !== "string") {
            throw(new UnexpectedValueException("Please use a URL string of the resource link"));
        }
        
        //check that string is a valid URL
        if(filter_var($newResourceLink, FILTER_VALIDATE_URL) === false) {
            throw(new UnexpectedValueException("Please use a valid URL link"));   
        }
        
        $splitResourceLink = explode ("://", $newResourceLink);
        if(strtolower($splitResourceLink[0]) !== "http" || strtolower($splitResourceLink[0]) !== "https") {
            throw(new UnexpectedValueException("Please use only Http and Https"));    
        }
        
        $splitResourceLink[1] = filter_var($splitResourceLink[1], FILTER_SANITIZE_STRING);
        
        $this->resourceLink = implode("://", $splitResourceLink);
    }
}

?>